import * as yup from 'yup'
const phoneNumber = /^[0-9]*$/;

export const yupValidate = yup.object({
    chuSoHuu: yup.string().required('Trường bắt buộc'),
    namSinh: yup.date().typeError('Không đúng định dạng').required('Trường bắt buộc'),
    quocGia: yup.object().required('Trường bắt buộc'),
    thanhPho: yup.object().required('Trường bắt buộc'),
    quanHuyen: yup.object().required('Trường bắt buộc'),
    phuongXa: yup.object().required('Trường bắt buộc'),
    diaChi: yup.string().required('Trường bắt buộc').max(200, 'Tối đa 50 ký tự'),
    cccdChuXe: yup.string().required('Trường bắt buộc').max(15, 'Tối đa 200 ký tự'),
    cccdChuXeCapNgay: yup.date().typeError('Không đúng định dạng').required('Trường bắt buộc'),
    cccdChuXeNoiCap: yup.object().required('Trường bắt buộc'),
    sdtChuXe: yup.string().matches(phoneNumber, 'only number').required('Trường bắt buộc'),
    cccdNltt: yup.string().required('Trường bắt buộc').max(15, 'Tối đa 200 ký tự'),
    cccdNlttCapNgay: yup.date().typeError('Không đúng định dạng'),
    cccdNlttNoiCap: yup.object(),
    sdtNltt: yup.string().typeError('Không đúng định dạng').matches(phoneNumber, 'only number').required('Trường bắt buộc'),
    khaiLPTB: yup.string().required('Trường bắt buộc'),
    coQuanCapLPTB: yup.object().required('Trường bắt buộc'),
    seriKTCLXX: yup.string().required('Trường bắt buộc'),
    coQuanCapKTCLXX: yup.object().required('Trường bắt buộc'),
    loaiXe: yup.object().required('Trường bắt buộc'),
    nhanHieu: yup.object().required('Trường bắt buộc'),
    soKhung: yup.string().required('Trường bắt buộc'),
    soMay1: yup.string().required('Trường bắt buộc'),
    soLoai: yup.string().required('Trường bắt buộc'),
    ngayDangKy: yup.date().typeError('Không đúng định dạng').required('Trường bắt buộc'),
    khuKinhTe: yup.object().required('Trường bắt buộc'),
    bienTheoTinh: yup.object().required('Trường bắt buộc'),
    bienQuocGia: yup.object().required('Trường bắt buộc'),
    seriChu: yup.object().required('Trường bắt buộc'),
    mauBien: yup.object().required('Trường bắt buộc'),
})