import * as yup from 'yup'
const phoneNumber = /(?<=src :)(.*)(?=;)/;

export const yupValidate = yup.object({
    chuSoHuu: yup.string().required('Trường bắt buộc').max(50, 'Tối đa 50 ký tự').min(4, 'tối thiểu 4 ký tự'),
    namSinh: yup.date("asdasdas").required('Trường bắt buộc').max(4, 'Tối đa 50 ký tự'),
    // quocGia: yup.object('').required('Trường bắt buộc'),
    // thanhPho: yup.object().required('Trường bắt buộc'),
    // quanHuyen: yup.object().required('Trường bắt buộc'),
    // phuongXa: yup.object().required('Trường bắt buộc'),
    diaChi: yup.string().required('Trường bắt buộc').max(200, 'Tối đa 50 ký tự'),
    cccdChuXe: yup.string().required('Trường bắt buộc').max(15, 'Tối đa 200 ký tự'),
    cccdChuXeCapNgay: yup.string().required('Trường bắt buộc'),
    cccdChuXeNoiCap: yup.string().required('Trường bắt buộc').max(60, 'Tối đa 60 ký tự'),
    sdtChuXe: yup.string().matches(phoneNumber, 'only number').required('Trường bắt buộc').max(13, 'Tối đa 13 ký tự'),
    cccdNltt: yup.string().required('Trường bắt buộc').max(15, 'Tối đa 200 ký tự'),
    cccdNlttCapNgay: yup.string().required('Trường bắt buộc'),
    cccdNlttNoiCap: yup.string().required('Trường bắt buộc').max(60, 'Tối đa 60 ký tự'),
    sdtNltt: yup.string().matches(phoneNumber, 'only number').required('Trường bắt buộc').max(13, 'Tối đa 13 ký tự'),
    khaiLPTB: yup.string().required('Trường bắt buộc').max(20, 'Tối đa 20 ký tự'),
    coQuanCapLPTB: yup.string().required('Trường bắt buộc').max(50, 'Tối đa 50 ký tự'),
    seriKTCLXX: yup.string().required('Trường bắt buộc').max(20, 'Tối đa 20 ký tự'),
    coQuanCapKTCLXX: yup.string().required('Trường bắt buộc').max(50, 'Tối đa 50 ký tự'),
    loaiXe: yup.string().required('Trường bắt buộc').max(50, 'Tối đa 50 ký tự'),
    nhanHieu: yup.string().required('Trường bắt buộc').max(50, 'Tối đa 50 ký tự'),
    soKhung: yup.string().required('Trường bắt buộc').max(25, 'Tối đa 25 ký tự'),
    soMay1: yup.string().required('Trường bắt buộc').max(25, 'Tối đa 25 ký tự'),
    soLoai: yup.string().required('Trường bắt buộc').max(18, 'Tối đa 50 ký tự'),
    ngayDangKy: yup.string().required('Trường bắt buộc'),
    kttmDacBiet: yup.string().required('Trường bắt buộc'),
    khuKinhTe: yup.string().required('Trường bắt buộc'),
    bienTheoTinh: yup.string().required('Trường bắt buộc').max(2, 'Tối đa 2 ký tự'),
    bienQuocGia: yup.string().required('Trường bắt buộc').max(3, 'Tối đa 3 ký tự'),
    seriChu: yup.string().required('Trường bắt buộc'),
    mauBien: yup.string().required('Trường bắt buộc'),
})